%% Initialize variables.
filename = 'C:\Users\Kevin\Desktop\PES\humidity.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
formatSpec = '%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
humidity = dataArray{:, 1};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Import data from text file.

%% Initialize variables.
filename = 'C:\Users\Kevin\Desktop\PES\temperature.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
formatSpec = '%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
Temperature = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Import data from text file.


%% Initialize variables.
filename = 'C:\Users\Kevin\Desktop\PES\present.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:

formatSpec = '%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.

dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
Distance = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


%% blabla
% Auto-generated by MATLAB on 2016/12/08 20:37:46

%% Initialize variables.
filename = 'C:\Users\Kevin\Desktop\PES\numberstate.csv';
delimiter = ',';
startRow = 2;
endRow = 3404;

%% Format string for each line of text:

formatSpec = '%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.

dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
State = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;

figure;
subplot(4,1,1);
plot(Temperature,'.');
ylabel('Temp [C°]','FontSize',10);
xlabel('Time [s]','FontSize',10);
hold on;
line = 25*ones(1,length(Temperature));
plot(line);
line = 20*ones(1,length(Temperature));
plot(line);
title('Temperature upper thresh: 25°C , down thresh: 20°C','FontSize',10);
subplot(4,1,2);
plot(humidity,'.');
ylabel('Humidity [%]','FontSize',10);
xlabel('Time [s]','FontSize',10);
hold on;
line = 30*ones(1,length(Temperature));
plot(line);
line = 25*ones(1,length(Temperature));
plot(line);
title('Humidity upper thresh: 30% , down thresh: 25%','FontSize',10);
subplot(4,1,3);
plot(Distance,'.');
ylabel('Distance [cm]','FontSize',15);
xlabel('Time [s]','FontSize',15);
hold on;
line = 30*ones(1,length(Temperature));
plot(line);
title('Distance thresh: 30 cm','FontSize',10);
subplot(4,1,4);
plot(State,'.');
title('State','FontSize',10);
xlabel('Time [s]','FontSize',10);
h = suptitle('Whole measurement over roughly 1 hour');
set(h,'FontSize',20,'FontWeight','normal')



%sry for everybode who wants to debug after this
Temperature = Temperature(1000:2500);
humidity = humidity(1000:2500);
Distance = Distance(1000:2500);
State = State(1000:2500);


figure;
subplot(4,1,1);
plot(Temperature,'.');
ylabel('Temp [C°]','FontSize',10);
xlabel('Time [s]','FontSize',10);
hold on;
line = 25*ones(1,length(Temperature));
plot(line);
line = 20*ones(1,length(Temperature));
plot(line);
title('Temperature upper thresh: 25°C , down thresh: 20°C','FontSize',10);
subplot(4,1,2);
plot(humidity,'.');
ylabel('Humidity [%]','FontSize',10);
xlabel('Time [s]','FontSize',10);
hold on;
line = 30*ones(1,length(Temperature));
plot(line);
line = 25*ones(1,length(Temperature));
plot(line);
title('Humidity upper thresh: 30% , down thresh: 25%','FontSize',10);
subplot(4,1,3);
plot(Distance,'.');
ylabel('Distance [cm]','FontSize',15);
xlabel('Time [s]','FontSize',15);
hold on;
line = 30*ones(1,length(Temperature));
plot(line);
title('Distance thresh: 30 cm','FontSize',10);
subplot(4,1,4);
plot(State,'.');
title('State','FontSize',10);
xlabel('Time [s]','FontSize',10);
h = suptitle('Whole measurement over roughly 1 hour');
set(h,'FontSize',20,'FontWeight','normal')








